import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight } from 'lucide-react'
import { signup } from '../../services/authService'
import { getApiError } from '../../services/api'

export default function Signup() {
  const navigate = useNavigate(); const [form, setForm] = useState({ employeeId: '', email: '', password: '', role: 'Employee', confirmPassword: '' }); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [loading, setLoading] = useState(false)
  const update = (key, value) => setForm({ ...form, [key]: value })
  const submit = async (event) => { event.preventDefault(); setError(''); setSuccess(''); if (Object.values(form).some((value) => !value)) return setError('Please complete every field.'); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) return setError('Enter a valid email address.'); if (form.password.length < 8) return setError('Password must be at least 8 characters.'); if (form.password !== form.confirmPassword) return setError('Passwords do not match.'); setLoading(true); try { await signup(form); setSuccess('Registration complete. Redirecting to sign in...'); setTimeout(() => navigate('/login'), 900) } catch (err) { setError(getApiError(err)) } finally { setLoading(false) } }
  return <div className="auth-layout"><div className="auth-aside"><div className="brand auth-brand"><span className="brand-mark">D</span><span>dayflow</span></div><div className="auth-quote"><div className="eyebrow">A BETTER WORKDAY</div><h1>Make space for the work that matters.</h1><p>Join your team’s single source of truth for the everyday details.</p></div><div className="auth-aside-footer">Employee workspace · Secure access</div></div><main className="auth-panel"><div className="auth-form-wrap signup-wrap"><div className="mobile-auth-brand brand"><span className="brand-mark">D</span><span>dayflow</span></div><div className="eyebrow">GET STARTED</div><h2>Create your account</h2><p className="muted">Your people team can help with your employee ID.</p><form onSubmit={submit} className="form-stack two-col"><label>Employee ID<input placeholder="EMP-0000" value={form.employeeId} onChange={(e) => update('employeeId', e.target.value)}/></label><label>Work email<input type="email" placeholder="you@company.com" value={form.email} onChange={(e) => update('email', e.target.value)}/></label><label>Password<input type="password" placeholder="8+ characters" value={form.password} onChange={(e) => update('password', e.target.value)}/></label><label>Confirm password<input type="password" placeholder="Repeat password" value={form.confirmPassword} onChange={(e) => update('confirmPassword', e.target.value)}/></label><label>Role<select value={form.role} onChange={(e) => update('role', e.target.value)}><option>Employee</option><option>HR</option></select></label>{error && <div className="form-error span-two">{error}</div>}{success && <div className="form-success span-two">{success}</div>}<button className="primary-button full span-two" disabled={loading}>{loading ? 'Creating account...' : <>Create account <ArrowRight size={17}/></>}</button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></div></main></div>
}
