import { useEffect, useState } from 'react'
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3 } from 'lucide-react'
import PageHeader from '../../components/PageHeader'
import Loading from '../../components/Loading'
import ErrorMessage from '../../components/ErrorMessage'
import StatusBadge from '../../components/StatusBadge'
import { checkIn, checkOut, getAttendance } from '../../services/attendanceService'
import { getApiError } from '../../services/api'
const unwrap = (result, key) => result?.[key] || result?.data?.[key] || result?.data || result || []
export default function Attendance() { const [data, setData] = useState(null); const [week, setWeek] = useState([]); const [loading, setLoading] = useState(true); const [action, setAction] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const load = async () => { setLoading(true); setError(''); try { const result = await getAttendance(); setData(unwrap(result, 'today') || {}); setWeek(unwrap(result, 'weekly') || unwrap(result, 'week') || []); } catch (err) { setError(getApiError(err)) } finally { setLoading(false) } }; useEffect(() => { load() }, []); const act = async (type) => { setAction(type); setMessage(''); try { await (type === 'in' ? checkIn() : checkOut()); setMessage(type === 'in' ? 'Check-in successful.' : 'Check-out successful.'); await load() } catch (err) { setError(getApiError(err)) } finally { setAction('') } }; if (loading) return <Loading label="Loading attendance..."/>; if (error && !data) return <ErrorMessage message={error} onRetry={load}/>; const rows = Array.isArray(data?.daily) ? data.daily : Array.isArray(data) ? data : data?.records || []; const canIn = !data?.checkIn && !data?.checkInTime; const canOut = !data?.checkOut && !data?.checkOutTime && !canIn
  return <><PageHeader eyebrow="TIME & ATTENDANCE" title="Attendance" description="Keep an accurate pulse on your workday."/><section className="attendance-hero"><div><div className="eyebrow">TODAY’S ATTENDANCE</div><h2>{data?.date || new Date().toLocaleDateString()}</h2><div className="attendance-status"><StatusBadge status={data?.status || 'Not recorded'}/>{data?.workingHours || data?.hours ? <span>{data.workingHours || data.hours} worked</span> : null}</div></div><div className="attendance-actions">{message && <span className="form-success compact">✓ {message}</span>}{error && <span className="form-error compact">{error}</span>}<button className="primary-button" disabled={!canIn || action} onClick={() => act('in')}>{action === 'in' ? 'Checking in...' : <><Check size={16}/> Check in</>}</button><button className="secondary-button" disabled={!canOut || action} onClick={() => act('out')}>{action === 'out' ? 'Checking out...' : 'Check out'}</button></div></section><section className="time-row large-time"><div><span><Clock3 size={14}/> Check-in</span><strong>{data?.checkIn || data?.checkInTime || '—'}</strong></div><div><span><Clock3 size={14}/> Check-out</span><strong>{data?.checkOut || data?.checkOutTime || '—'}</strong></div><div><span><CalendarDays size={14}/> Working hours</span><strong>{data?.workingHours || data?.hours || '—'}</strong></div></section><section className="section-card"><div className="card-heading"><div><div className="eyebrow">HISTORY</div><h2>Daily attendance</h2></div><div className="week-controls"><button className="icon-button" aria-label="Previous week"><ChevronLeft size={17}/></button><span>Current week</span><button className="icon-button" aria-label="Next week"><ChevronRight size={17}/></button></div></div><div className="table-scroll"><table><thead><tr><th>Date</th><th>Check-in</th><th>Check-out</th><th>Status</th></tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={row._id || row.id || index}><td>{row.date || row.day || '—'}</td><td>{row.checkIn || row.checkInTime || '—'}</td><td>{row.checkOut || row.checkOutTime || '—'}</td><td><StatusBadge status={row.status}/></td></tr>) : <tr><td colSpan="4" className="empty-cell">No attendance records returned.</td></tr>}</tbody></table></div></section><section className="section-card"><div className="eyebrow">WEEKLY VIEW</div><h2 className="card-title">This week</h2><div className="week-grid">{week.length ? week.map((day, index) => <div key={day.date || index}><span>{day.day || day.date}</span><StatusBadge status={day.status}/></div>) : <p className="muted">Weekly attendance will appear when the backend returns it.</p>}</div></section></>
}
