import { useEffect, useState } from 'react'
import { Send } from 'lucide-react'
import PageHeader from '../../components/PageHeader'
import Loading from '../../components/Loading'
import ErrorMessage from '../../components/ErrorMessage'
import StatusBadge from '../../components/StatusBadge'
import { applyLeave, getLeaves } from '../../services/leaveService'
import { getApiError } from '../../services/api'
const unwrap = (result) => result?.leaves || result?.data?.leaves || result?.data || result || []
export default function Leave() { const [leaves, setLeaves] = useState([]); const [form, setForm] = useState({ leaveType: '', startDate: '', endDate: '', remarks: '' }); const [state, setState] = useState({ loading: true, submitting: false, error: '', message: '' }); const load = async () => { setState({ ...state, loading: true, error: '' }); try { setLeaves(unwrap(await getLeaves())) } catch (err) { setState({ ...state, loading: false, error: getApiError(err) }); return } setState({ ...state, loading: false }) }; useEffect(() => { load() }, []); const submit = async (event) => { event.preventDefault(); if (!form.leaveType || !form.startDate || !form.endDate) return setState({ ...state, error: 'Choose a leave type and both dates.' }); if (form.endDate < form.startDate) return setState({ ...state, error: 'End date cannot be before start date.' }); setState({ ...state, submitting: true, error: '', message: '' }); try { await applyLeave(form); setForm({ leaveType: '', startDate: '', endDate: '', remarks: '' }); setState({ ...state, submitting: false, message: 'Leave request submitted successfully.' }); await load() } catch (err) { setState({ ...state, submitting: false, error: getApiError(err) }) } }
  if (state.loading) return <Loading label="Loading leave history..."/>; if (state.error && !leaves.length) return <ErrorMessage message={state.error} onRetry={load}/>; return <><PageHeader eyebrow="TIME AWAY" title="Leave" description="Plan time away and keep track of every request."/><div className="leave-grid"><section className="section-card"><div className="eyebrow">NEW REQUEST</div><h2 className="card-title">Apply for leave</h2><form onSubmit={submit} className="form-stack"><label>Leave type<select value={form.leaveType} onChange={(e) => setForm({ ...form, leaveType: e.target.value })}><option value="">Select type</option><option value="Paid">Paid</option><option value="Sick">Sick</option><option value="Unpaid">Unpaid</option></select></label><div className="two-col"><label>From date<input type="date" value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })}/></label><label>To date<input type="date" value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })}/></label></div><label>Remarks <span className="optional">Optional</span><textarea rows="4" placeholder="Add context for your manager" value={form.remarks} onChange={(e) => setForm({ ...form, remarks: e.target.value })}/></label>{state.error && <div className="form-error">{state.error}</div>}{state.message && <div className="form-success">{state.message}</div>}<button className="primary-button" disabled={state.submitting}>{state.submitting ? 'Submitting...' : <><Send size={16}/> Submit request</>}</button></form></section><section className="section-card"><div className="eyebrow">REQUESTS</div><h2 className="card-title">Leave history</h2><div className="table-scroll"><table><thead><tr><th>Type</th><th>From</th><th>To</th><th>Status</th></tr></thead><tbody>{leaves.length ? leaves.map((leave, index) => <tr key={leave._id || leave.id || index}><td>{leave.leaveType || leave.type || '—'}</td><td>{leave.startDate || leave.from || '—'}</td><td>{leave.endDate || leave.to || '—'}</td><td><StatusBadge status={leave.status}/></td></tr>) : <tr><td colSpan="4" className="empty-cell">No leave requests yet.</td></tr>}</tbody></table></div></section></div></>
}
