import { useEffect, useState } from 'react'
import { CircleDollarSign, Download } from 'lucide-react'
import PageHeader from '../../components/PageHeader'
import Loading from '../../components/Loading'
import ErrorMessage from '../../components/ErrorMessage'
import { getPayroll } from '../../services/payrollService'
import { getApiError } from '../../services/api'
const unwrap = (result) => result?.payroll || result?.data?.payroll || result?.data || result || {}
export default function Payroll() { const [payroll, setPayroll] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const load = async () => { setLoading(true); setError(''); try { setPayroll(unwrap(await getPayroll())) } catch (err) { setError(getApiError(err)) } finally { setLoading(false) } }; useEffect(() => { load() }, []); if (loading) return <Loading label="Loading payroll..."/>; if (error) return <ErrorMessage message={error} onRetry={load}/>; const money = (value) => value === undefined || value === null || value === '' ? '—' : value; return <><PageHeader eyebrow="COMPENSATION" title="Payroll" description="A clear view of your current salary information."/><section className="payroll-banner"><div className="payroll-icon"><CircleDollarSign size={23}/></div><div><span>NET SALARY</span><strong>{money(payroll?.netSalary || payroll?.net_salary)}</strong><small>Current pay period</small></div></section><section className="section-card payroll-card"><div className="card-heading"><div><div className="eyebrow">PAY BREAKDOWN</div><h2>Employee payroll</h2></div><button className="secondary-button" disabled title="Available when payroll documents are provided"><Download size={16}/> Download</button></div><div className="payroll-details"><div><span>Employee</span><strong>{payroll?.employeeName || payroll?.name || '—'}</strong></div><div><span>Employee ID</span><strong>{payroll?.employeeId || '—'}</strong></div><div><span>Basic salary</span><strong>{money(payroll?.basicSalary || payroll?.basic_salary)}</strong></div><div><span>Allowances</span><strong>{money(payroll?.allowances)}</strong></div><div><span>Deductions</span><strong>{money(payroll?.deductions)}</strong></div></div></section></> }
