import { useEffect, useState } from 'react'
import { Save, UserRound } from 'lucide-react'
import PageHeader from '../../components/PageHeader'
import Loading from '../../components/Loading'
import ErrorMessage from '../../components/ErrorMessage'
import { getProfile, updateProfile } from '../../services/profileService'
import { getApiError } from '../../services/api'

const unwrap = (result) => result?.profile || result?.data?.profile || result?.data || result || {}
export default function Profile() { const [profile, setProfile] = useState(null); const [form, setForm] = useState({ phone: '', address: '', profilePicture: '' }); const [state, setState] = useState({ loading: true, saving: false, error: '', message: '' }); const load = async () => { setState({ ...state, loading: true, error: '' }); try { const next = unwrap(await getProfile()); setProfile(next); setForm({ phone: next.phone || '', address: next.address || '', profilePicture: next.profilePicture || next.profileImage || '' }) } catch (err) { setState({ ...state, loading: false, error: getApiError(err) }); return } setState({ ...state, loading: false }) }; useEffect(() => { load() }, [])
  const save = async (event) => { event.preventDefault(); setState({ ...state, saving: true, message: '', error: '' }); try { const next = unwrap(await updateProfile(form)); setProfile(next || { ...profile, ...form }); setState({ ...state, saving: false, message: 'Profile updated successfully.' }) } catch (err) { setState({ ...state, saving: false, error: getApiError(err) }) } }
  if (state.loading) return <Loading label="Loading profile..."/>; if (state.error && !profile) return <ErrorMessage message={state.error} onRetry={load}/>; const readOnly = [['Employee ID', profile.employeeId || profile.id], ['Email', profile.email], ['Department', profile.department], ['Designation', profile.designation], ['Joining date', profile.joiningDate || profile.joinedAt]]
  return <><PageHeader eyebrow="MY PROFILE" title="Profile" description="Your identity at Dayflow, all in one place."/><div className="profile-grid"><section className="section-card profile-card"><div className="profile-hero"><div className="avatar large">{(profile.name || profile.fullName || 'E').slice(0,1)}</div><div><h2>{profile.name || profile.fullName || 'Employee'}</h2><p>{profile.designation || 'Employee'}</p></div></div><div className="eyebrow profile-label">PERSONAL DETAILS</div><form onSubmit={save} className="form-stack"><label>Phone<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })}/></label><label>Address<textarea rows="3" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })}/></label><label>Profile picture URL<input value={form.profilePicture} onChange={(e) => setForm({ ...form, profilePicture: e.target.value })} placeholder="https://..."/></label>{state.error && <div className="form-error">{state.error}</div>}{state.message && <div className="form-success">{state.message}</div>}<button className="primary-button" disabled={state.saving}><Save size={16}/>{state.saving ? 'Saving...' : 'Save changes'}</button></form></section><section className="section-card"><div className="eyebrow">EMPLOYMENT DETAILS</div><h2 className="card-title">Read-only information</h2><div className="detail-list">{readOnly.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value || '—'}</strong></div>)}</div><div className="eyebrow profile-label">SALARY</div><div className="salary-readonly"><span>Current salary structure</span><strong>{profile.salary?.netSalary || profile.salary || 'Available through payroll'}</strong></div></section></div></>
}
